# image will be published to ghcr.io/<user>/<name>
name: toasty-os
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 40 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
                       # put configuration files you want in /usr/etc/ inside the image
                       # while putting files in /etc/ is done on booted system by system administrators.
                       # read more about this in files module reference.

  - type: rpm-ostree
    repos:
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/ryanabx/cosmic-epoch/repo/fedora-$(rpm -E %fedora)/ryanabx-cosmic-epoch-fedora-$(rpm -E %fedora).repo
    install:
      # - micro
      # - starship
      - zsh
      - eza
      - curl
      - wget
      - git
      - gnome-tweaks
      - google-tinos-fonts
      - google-cousine-fonts
      - google-arimo-fonts
      - google-crosextra-caladea-fonts
      - google-carlito-fonts
      - ibm-plex-fonts-all
      - adw-gtk3
      # TODO: remove cosmic-desktop when stable enough to be its own DE or when give up on testing it out
      # terrible to do since silverblue but wanna test out cosmic so until it comes out officialy for an official spin or maybe a beta version gotta deal with this
      - cosmic-desktop
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
       - firefox
       - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
       - gnome-shell-extension-background-logo

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - com.github.johnfactotum.Foliate
        - com.github.maoschanz.drawing
        # sometime should probably see the alternatives and see if better than clapper
        - com.github.rafostar.Clapper
        - com.obsproject.Studio.Plugin.Gstreamer
        - com.github.tchx84.Flatseal
        - com.github.wwmm.easyeffects
        - com.mattjakeman.ExtensionManager
        - com.spotify.Client
        - com.valvesoftware.Steam
        - dev.vencord.Vesktop
        - md.obsidian.Obsidian
        # org.freedesktop.LinuxAudio.Plugins.Calf
        # org.freedesktop.LinuxAudio.Plugins.LSP
        # org.freedesktop.LinuxAudio.Plugins.MDA
        # org.freedesktop.LinuxAudio.Plugins.ZamPlugins
        - org.freedesktop.Platform.ffmpeg-full
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
        - io.missioncenter.MissionCenter
        - app.devsuite.Ptyxis
        # usually gnome default apps but in flatpak instead of native
        - org.gnome.Calculator
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.clocks
        - org.gnome.Connections
        - org.gnome.Contacts
        - org.gnome.font-viewer
        - org.gnome.Logs
        - org.gnome.Maps
        - org.gnome.NautilusPreviewer
        - org.gnome.TextEditor
        - org.gnome.Weather
        # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08),
      # only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Installing different branches of the same Flatpak is not supported.
      remove:
      # - org.gnome.eog

- type: akmods
  base: main # if not specified, classic "main" base is used by default
  install:
    - v4l2loopback

- type: gschema-overrides
  include:
    - zz1-myoverride.gschema.override

- type: gnome-extensions
  install:
    # AppIndicator and KStatusNotifierItem Support
    - 615
    # Rounded Window Corners Reborn
    - 7048
    

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

